In [1]:
from sklearn.preprocessing import LabelEncoder

In [3]:
data=["small","medium","large","medium"]
le=LabelEncoder()
encoded=le.fit_transform(data)
print(encoded)

[2 1 0 1]


In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
import numpy as np

In [12]:
data=np.array([["red"],["blue"],["green"]])
encoder=OneHotEncoder()
encoded=encoder.fit_transform(data).toarray()
print(encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [13]:
import pandas as pd

In [16]:
df=pd.DataFrame({
    "city":["kochi","delhi","chennai","kochi"]
})
df_dummy=pd.get_dummies(df,drop_first=True)
print(df_dummy)

   city_delhi  city_kochi
0       False        True
1        True       False
2       False       False
3       False        True
